[WIP]: Add interface to manage mini sites
metanorma/metanorma-cli pull request #180
Opened 2020-10-17 09:46 UTC by abunashir

[Work In Progredss]

This commit is a placeholder for now, idea with this one is to merge all the site interface related sub-command to this one.
Once these subcommands are merged then we will merge this one to the master.

Related #130

2020-11-14 13:17 UTC, abunashir commented
Hi @ronaldtse: this is the initial PR that should generate a mini-site for any provided `source` directory, and it also respects that configuration file, could you please have a look and let me know your thoughts?

2020-11-20 10:56 UTC, abunashir commented
@ronaldtse: This PR is ready to review, let me know if there is anything else.

2020-12-01 13:09 UTC, abunashir commented
ping @ronaldtse

2020-12-03 17:17 UTC, ronaldtse commented
@abunashir here are the issues:

* When the output path is unspecified, it defaults to `site`, but the end message writes:
```sh
...
Site has been generated at 
#                                             ^== this is empty 
$ ...
```

* The program should write out in the console what document is being processed, and another message when the document is complete (or failed)

* I can't seem to use the configuration file.

manifest.yml
```yaml
---
metanorma:
  source:
    files:
      - T-REC-J.1108-201901-P.MSW-E.adoc

relaton:
  collection:
    organization: "Metanorma : Organization name sample"
    name: "Metanorma: Sample collection name from metanorma.yml"
```

My command:
```
bundle exec ./exe/metanorma site generate ../mn-templates-itu/sources -o site -c manifest.yml
```

=> Still generates all `*.adoc` inside `../mn-templates-itu/sources`

It should only read `../mn-template-itu/sources/T-REC-J.1108-201901-P.MSW-E.adoc` to build the site.

* Can you also add documentation on what parameters are optional and mandatory for this command? Thanks.

2020-12-03 17:17 UTC, ronaldtse requested changes
See comments.

2020-12-04 07:51 UTC, ronaldtse requested changes

2020-12-04 07:51 UTC, ronaldtse commented on spec/fixtures/metanorma.yml
> +      - ./sample.adoc
How about we add one more document sample here?

2020-12-04 11:17 UTC, abunashir commented
Good catch, I will fix it.
> @abunashir here are the issues:
> 
> * When the output path is unspecified, it defaults to `site`, but the end message writes:
> 
> ```shell
> ...
> Site has been generated at 
> #                                             ^== this is empty 
> $ ...
> ```
> 
> * The program should write out in the console what document is being processed, and another message when the document is complete (or failed)



Regarding the config file, I think I got it wrong. Currently, it's using a relative path for files from where the manifest file is, and it's including these custom files along with all the other files in the source directory, but let e clarify if I understand correctly, so if a file is in the manifest then we only want to compile that one and ignore others in the source directory right?


> * I can't seem to use the configuration file.
> 
> manifest.yml
> 
> ```yaml
> ---
> metanorma:
>   source:
>     files:
>       - T-REC-J.1108-201901-P.MSW-E.adoc
> 
> relaton:
>   collection:
>     organization: "Metanorma : Organization name sample"
>     name: "Metanorma: Sample collection name from metanorma.yml"
> ```
> 
> My command:
> 
> ```
> bundle exec ./exe/metanorma site generate ../mn-templates-itu/sources -o site -c manifest.yml
> ```
> 
> => Still generates all `*.adoc` inside `../mn-templates-itu/sources`
> 
> It should only read `../mn-template-itu/sources/T-REC-J.1108-201901-P.MSW-E.adoc` to build the site.
> 

Sure thing 👍 
> * Can you also add documentation on what parameters are optional and mandatory for this command? Thanks.

//@ronaldtse

2020-12-07 08:25 UTC, ronaldtse commented
> Regarding the config file, I think I got it wrong. Currently, it's using a relative path for files from where the manifest file is, and it's including these custom files along with all the other files in the source directory, but let e clarify if I understand correctly, so if a file is in the manifest then we only want to compile that one and ignore others in the source directory right?

Yes. If a manifest is provided, it should only act on the source files listed in the manifest.

Thanks!

2020-12-07 18:13 UTC, abunashir commented
@ronaldtse: Just updated the PR with the requested changes, could you please have another look?

2020-12-10 04:23 UTC, ronaldtse commented
Error encountered:
```
bundle exec metanorma site generate ../mn-samples-itu -o output -c manifest.yml 
Deprecation warning: Expected string default value for '--output-dir'; got #<Pathname:/Users/me/src/mn/metanorma-cli/site> ().
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
[info]: Compiling /Users/me/src/mn/metanorma-cli/T-REC-J.1108-201901-P.MSW-E.adoc ...
Error: Specified input file '/Users/me/src/mn/metanorma-cli/T-REC-J.1108-201901-P.MSW-E.adoc' does not exist. 
Not sure what to run? try: metanorma help
```

Ping @abunashir 

Content of manifest.yml:
```yaml
---
metanorma:
  source:
    files:
      - T-REC-J.1108-201901-P.MSW-E.adoc

relaton:
  collection:
    organization: "Metanorma : Organization name sample"
    name: "Metanorma: Sample collection name from metanorma.yml"
```

The `-o` and `-c` options should be useable independently, in addition to together.

For example:
```
# source path: current directory; output path {current directory}/my_output
metanorma site generate . -o my_output

# source path: current directory; config: manifest.yml
metanorma site generate . -c manifest.yml

# source path: current directory; output path {current directory}/my_output; config: manifest.yml
metanorma site generate . -o my_output -c manifest.yml
```

The manifest file "source" should be relative paths based on the "source directory". i.e. when I specified `T-REC-J.1108-201901-P.MSW-E.adoc` in the file above, it should be treated as the file path `{specified source directory}/T-REC-J.1108-201901-P.MSW-E.adoc`. Right now it is considered `{pwd}/T-REC-J.1108-201901-P.MSW-E.adoc`

2020-12-10 04:23 UTC, ronaldtse submitted a review, later dismissed
As stated in comment.

2020-12-11 15:33 UTC, abunashir commented
@ronaldtse: Yes, the current version is using the directory of the configuration file and try to join the source files listed there relative to that directory but not the source directory. I will update it now so it will take the source directory into consideration.

The `ensure_site_asset_directory!` should ensure the creation of all necessary folder structure or raise permission error, but I will double-check everything.

2020-12-11 15:52 UTC, abunashir commented
Updated the following command should work fine now, but let me know if there is any other issues.

```sh
bundle exec metanorma site generate ../mn-samples-itu/sources -o output -c manifest.yml
```

2020-12-12 06:29 UTC, ronaldtse commented
@abunashir thanks! Will merge this first since it's working. Could you help make documentation on how to use the Manifest/Config file to build the site? For example, can we support wildcards? Will be new issue.

2020-12-12 06:37 UTC, merged