Explicitly activate all flavored gems
metanorma/metanorma-cli pull request #230
Opened 2021-03-13 14:37 UTC by abunashir

There has been a long pending issue with the performance for the cli, especially if we have multiple version installed. In that case lots of gem still stays as unresolved, and that cause some of the performance issue.

This commit follows some suggestion to explicitly activate those gems, as it should resolve the dependencies early.

2021-05-05 15:10 UTC, abunashir commented
*Fair warning*: 

We want to test this out with our next release to see if that helps in-terms of performance but if there is any issue occurs related to gem loading - then please let me know.

2021-05-05 15:20 UTC, CAMOBAP approved these changes
LGTM

2021-05-06 06:20 UTC, ronaldtse requested changes

2021-05-06 06:20 UTC, ronaldtse commented on lib/metanorma/flavor.rb
> +      "metanorma-nist",
@abunashir please help remove this, it's a private gem.

2021-05-07 14:49 UTC, merged